# Generated by Django 3.1.2 on 2020-11-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnasearch_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnasearch',
            name='completed_at',
            field=models.DateTimeField(null=True, verbose_name='datetime search was completed'),
        ),
        migrations.AlterField(
            model_name='dnasearch',
            name='result_end_location',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dnasearch',
            name='result_protein',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='dnasearch',
            name='result_start_location',
            field=models.IntegerField(null=True),
        ),
    ]
